/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class GestionEnviosPanel extends javax.swing.JPanel {
    
    private final PrincipalFrame principalFrame;

    /**
     * Creates new form PrincipalPanel
     *
     * @param principalFrame
     */
    public GestionEnviosPanel(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
        //Todo
        cargarUsuarios();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonLimpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTituloUsuario = new javax.swing.JLabel();
        jScrollPaneUsuario = new javax.swing.JScrollPane();
        jTextAreaUsuario = new javax.swing.JTextArea();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        jButtonCargarUsuario = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jLabelDatosRemitente = new javax.swing.JLabel();
        jLabelNombreRemitente = new javax.swing.JLabel();
        jTextFieldNombreRemitente = new javax.swing.JTextField();
        jLabelCedulaRemitente = new javax.swing.JLabel();
        jTextFieldCedulaRemitente = new javax.swing.JTextField();
        jLabelTelefonoRemitente = new javax.swing.JLabel();
        jTextFieldTelefonoRemitente = new javax.swing.JTextField();
        jLabelEdadRemitente = new javax.swing.JLabel();
        jTextFieldEdadRemitente = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelDatosDestinatario = new javax.swing.JLabel();
        jLabelNombreDestinatario = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNombreDestinatario = new javax.swing.JTextField();
        jTextFieldTelefonoDestinatario = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jLabelEdadDestinatario = new javax.swing.JLabel();
        jTextFieldCedulaDestinatario = new javax.swing.JTextField();
        jTextFieldEdadDestinatario = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabelDatosPaquete = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();
        jTextFieldCosto = new javax.swing.JTextField();
        jTextFieldPeso = new javax.swing.JTextField();
        jDateFechaEntrega = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Gestion de Envios");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 11, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 636, 10));

        jButtonLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 10, 320));

        jLabelTituloUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTituloUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloUsuario.setText("Envios");
        add(jLabelTituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jTextAreaUsuario.setEditable(false);
        jTextAreaUsuario.setColumns(20);
        jTextAreaUsuario.setRows(5);
        jScrollPaneUsuario.setViewportView(jTextAreaUsuario);

        add(jScrollPaneUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 338, 137));

        jComboBoxUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja un Envio" }));
        jComboBoxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsuarioActionPerformed(evt);
            }
        });
        add(jComboBoxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 245, -1));

        jButtonCargarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCargarUsuario.setText("Cargar");
        jButtonCargarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarUsuarioActionPerformed(evt);
            }
        });
        add(jButtonCargarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabelDatosRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosRemitente.setText("Datos del Remitente");
        add(jLabelDatosRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabelNombreRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelNombreRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreRemitente.setText("Nombre:");
        add(jLabelNombreRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        add(jTextFieldNombreRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 170, -1));

        jLabelCedulaRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCedulaRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCedulaRemitente.setText("Cedula:");
        add(jLabelCedulaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        add(jTextFieldCedulaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 170, -1));

        jLabelTelefonoRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelTelefonoRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefonoRemitente.setText("Telefono:");
        add(jLabelTelefonoRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        add(jTextFieldTelefonoRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 50, -1));

        jLabelEdadRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelEdadRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadRemitente.setText("Edad:");
        add(jLabelEdadRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));
        add(jTextFieldEdadRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 60, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 20));

        jLabelDatosDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosDestinatario.setText("Datos del Destinatario");
        add(jLabelDatosDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabelNombreDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelNombreDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreDestinatario.setText("Nombre:");
        add(jLabelNombreDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono:");
        add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        add(jTextFieldNombreDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 170, -1));
        add(jTextFieldTelefonoDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 60, -1));

        jLabelCedula.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCedula.setText("Cedula:");
        add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabelEdadDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelEdadDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadDestinatario.setText("Edad:");
        add(jLabelEdadDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
        add(jTextFieldCedulaDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 170, -1));
        add(jTextFieldEdadDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 50, -1));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 10));

        jLabelDatosPaquete.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosPaquete.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosPaquete.setText("Datos del Paquete");
        add(jLabelDatosPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelCodigo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Codigo:");
        add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 49, -1));
        add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 380));
        add(jTextFieldCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(jDateFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCargarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarUsuarioActionPerformed
        cargarDatosDelUsuario();
    }//GEN-LAST:event_jButtonCargarUsuarioActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        modificarUsuario();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jComboBoxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarUsuario;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private com.toedter.calendar.JDateChooser jDateFechaEntrega;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCedulaRemitente;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDatosDestinatario;
    private javax.swing.JLabel jLabelDatosPaquete;
    private javax.swing.JLabel jLabelDatosRemitente;
    private javax.swing.JLabel jLabelEdadDestinatario;
    private javax.swing.JLabel jLabelEdadRemitente;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombreDestinatario;
    private javax.swing.JLabel jLabelNombreRemitente;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoRemitente;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloUsuario;
    private javax.swing.JScrollPane jScrollPaneUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextAreaUsuario;
    private javax.swing.JTextField jTextFieldCedulaDestinatario;
    private javax.swing.JTextField jTextFieldCedulaRemitente;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldEdadDestinatario;
    private javax.swing.JTextField jTextFieldEdadRemitente;
    private javax.swing.JTextField jTextFieldNombreDestinatario;
    private javax.swing.JTextField jTextFieldNombreRemitente;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldTelefonoDestinatario;
    private javax.swing.JTextField jTextFieldTelefonoRemitente;
    // End of variables declaration//GEN-END:variables
   
    private void limpiar() {
        this.jTextFieldCodigo.setText("");
        this.jTextFieldCedulaDestinatario.setText("");
        this.jTextFieldCedulaRemitente.setText("");
        this.jTextFieldNombreDestinatario.setText("");
        this.jTextFieldNombreRemitente.setText("");
        this.jTextFieldNombreRemitente.requestFocus();
        this.jTextFieldEdadDestinatario.setText("");
        this.jTextFieldEdadRemitente.setText("");
        this.jTextFieldTelefonoDestinatario.setText("");
        this.jTextFieldTelefonoRemitente.setText("");
        this.jTextFieldPeso.setText("");
        this.jTextFieldCosto.setText("");
        this.jDateFechaEntrega.setDateFormatString("");
        jComboBoxUsuario.setSelectedIndex(0);
    }

    private void cargarDatosDelUsuario() {
        if (validarCargar()) {
                String[] datosPaquete = principalFrame.obtenerDatosDelEnvio((String) jComboBoxUsuario.getSelectedItem());
                jTextFieldCodigo.setText(datosPaquete[0]);
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNombreRemitente.setText(datosPaquete[1]);
                jTextFieldCedulaRemitente.setText(datosPaquete[2]);
                jTextFieldEdadRemitente.setText(datosPaquete[3]);
                jTextFieldTelefonoRemitente.setText(datosPaquete[4]);
                jTextFieldNombreDestinatario.setText(datosPaquete[5]);
                jTextFieldCedulaDestinatario.setText(datosPaquete[6]);
                jTextFieldEdadDestinatario.setText(datosPaquete[7]);
                jTextFieldTelefonoDestinatario.setText(datosPaquete[8]);
                jDateFechaEntrega.setDateFormatString(datosPaquete[9]);
                jTextFieldPeso.setText(datosPaquete[10]);
                jTextFieldCosto.setText(datosPaquete[11]);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Usuario", "Ver Usuario", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private boolean validar() {
        if (this.jTextFieldCodigo.getText().equals("")) {
            return false;
        }  else if (this.jTextFieldCedulaDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldCedulaRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldNombreDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldNombreRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldEdadDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldEdadRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldTelefonoDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldTelefonoRemitente.getText().equals("")) {
            return false;
        } else {
            return true;
        } 
    }
    
    private boolean validarCargar() {
        return jComboBoxUsuario.getSelectedIndex() > 0;
    }
    

    private void modificarUsuario() {
        if (validar()) {
            String codigo = jTextFieldCodigo.getText();
            String NombresRemitente = jTextFieldNombreRemitente.getText();
            String cedula = jTextFieldCedulaRemitente.getText();
            String edad = jTextFieldEdadRemitente.getText();
            String teléfono = jTextFieldTelefonoRemitente.getText();
            String NombreDestinatario = jTextFieldNombreDestinatario.getText();
            String cedula1 = jTextFieldCedulaDestinatario.getText();
            String edad1 = jTextFieldEdadDestinatario.getText();
            String teléfono1 = jTextFieldTelefonoDestinatario.getText();
            String Fechaentrega = jDateFechaEntrega.getDateFormatString();
            String peso = jTextFieldPeso.getText();
            int origen = 0;
            int destino = 0;
            if (!principalFrame.modificarEnvio(codigo, NombresRemitente, cedula, edad, teléfono, NombreDestinatario, cedula1, edad1, teléfono1,  Fechaentrega, peso,origen,destino)) {
                JOptionPane.showMessageDialog(this, "no se pudo modificar el Paquete", "Modificar", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Paquete "+codigo+" fue Modificado", "Modificar", JOptionPane.INFORMATION_MESSAGE);
                principalFrame.irAHome();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos requeridos para modificar  el Paquete", "Modificar", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void cargarUsuarios() {
        jTextFieldCodigo.requestFocus();
        jTextAreaUsuario.setText("");
        jTextAreaUsuario.setText(principalFrame.obtenerEnviosToString());
        jComboBoxUsuario.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione un Usuario"}));
        String[] items = new String[principalFrame.cantidadDeEnvios()+ 1];
        System.out.println(principalFrame.obtenerEnviosToString());
        System.out.println(principalFrame.cantidadDeEnvios()+ 1);
        items[0] = "Seleccione un Usuario";
        String[] usuarios = principalFrame.obtenerEnviosToStringArray();
        for (int i = 1; i < items.length; i++) {
            items[i] = usuarios[i - 1];
        }
        jComboBoxUsuario.setModel(new DefaultComboBoxModel<>(items));
    }
    
}
