/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class HomePanelAdministrador extends javax.swing.JPanel {
    
    private final PrincipalFrame principalFrame;

    /**
     * Creates new form PrincipalPanel
     *
     * @param principalFrame
     */
    public HomePanelAdministrador(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
        //cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelListas = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonSalir1 = new javax.swing.JButton();
        jButtonSalir2 = new javax.swing.JButton();
        jButtonSalir3 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Bienvenido a Gestion");
        add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 11, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 370, 10));

        jLabelListas.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabelListas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelListas.setText("¿Qué desea hacer?");
        add(jLabelListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 98, -1, -1));

        jButtonRegistrar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar Envio");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 139, -1));

        jButtonModificar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonModificar.setText("Modificar Paquete");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, -1, -1));

        jButtonEliminar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar Paquete");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, 139, -1));

        jButtonSalir.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonSalir.setText("Mineria de Datos");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 139, -1));

        jButtonSalir1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonSalir1.setText("Salir");
        jButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir1ActionPerformed(evt);
            }
        });
        add(jButtonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 139, -1));

        jButtonSalir2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonSalir2.setText("Mineria de Datos 3");
        jButtonSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir2ActionPerformed(evt);
            }
        });
        add(jButtonSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 150, -1));

        jButtonSalir3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonSalir3.setText("Mineria de Datos 2");
        jButtonSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir3ActionPerformed(evt);
            }
        });
        add(jButtonSalir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        modificar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        principalFrame.irAMineriaDatosPanel();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir1ActionPerformed
        principalFrame.salir();
    }//GEN-LAST:event_jButtonSalir1ActionPerformed

    private void jButtonSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir2ActionPerformed
        principalFrame.irAMineriaDatos3Panel();
    }//GEN-LAST:event_jButtonSalir2ActionPerformed

    private void jButtonSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir3ActionPerformed
        principalFrame.irAMineriaDatos2Panel();
    }//GEN-LAST:event_jButtonSalir3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JButton jButtonSalir2;
    private javax.swing.JButton jButtonSalir3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelListas;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void registrar() {
        principalFrame.irARegistroEnvioPanel();
    }

    private void modificar() {
        principalFrame.irAGestionEnvioPanel();
    }

    private void eliminar() {
        String respuesta = JOptionPane.showInputDialog(null, "Ingrese el Codigo del Paquete a Eliminar", "Eliminar", JOptionPane.DEFAULT_OPTION);
        if (principalFrame.existeEnvio(respuesta)) {
                principalFrame.EliminarEnvio(respuesta);
                JOptionPane.showMessageDialog(this, "EL Paquete se a eliminado Exitosamente", "Eliminar", JOptionPane.WARNING_MESSAGE);
        } else {
                JOptionPane.showMessageDialog(this, "No coincide el codigo ingresado con algun paquete existente", "Eliminar", JOptionPane.WARNING_MESSAGE);
        }
    }
    
}
