/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class HomePanelRegistrador extends javax.swing.JPanel {
    
    private final PrincipalFrame principalFrame;

    /**
     * Creates new form PrincipalPanel
     *
     * @param principalFrame
     */
    public HomePanelRegistrador(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
        //cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelListas = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonSalir1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Bienvenido a Gestion");
        add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 11, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 370, 10));

        jLabelListas.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabelListas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelListas.setText("¿Qué desea hacer?");
        add(jLabelListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 98, -1, -1));

        jButtonRegistrar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonRegistrar.setText("Añadir Estado");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 139, -1));

        jButtonSalir.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 139, -1));

        jButtonSalir1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButtonSalir1.setText("Ver Envio ");
        jButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir1ActionPerformed(evt);
            }
        });
        add(jButtonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 139, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 370, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        principalFrame.salir();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir1ActionPerformed
        principalFrame.irARegistroEstadoPanel();
    }//GEN-LAST:event_jButtonSalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelListas;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void registrar() {
        principalFrame.irAGestionEstadoPanel();
    }
    
}
