/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.vista;

import java.util.Set;
import redis.clients.jedis.Jedis;

/**
 *
 * @author sala1
 */
public class MineriaDatos2Panel extends javax.swing.JPanel {

    private final PrincipalFrame principalFrame;

    /**
     * Creates new form RegistroPanel
     *
     * @param principalFrame
     */
    public MineriaDatos2Panel(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelMatrizInicial = new javax.swing.JLabel();
        jScrollPaneUsuario1 = new javax.swing.JScrollPane();
        jTextAreaCiudad = new javax.swing.JTextArea();
        jLabelMatrizActualizada = new javax.swing.JLabel();
        jScrollPaneUsuario = new javax.swing.JScrollPane();
        jTextAreaCiudad1 = new javax.swing.JTextArea();
        jLabelMatrizActualizada1 = new javax.swing.JLabel();
        jScrollPaneUsuario2 = new javax.swing.JScrollPane();
        jTextAreaCiudad2 = new javax.swing.JTextArea();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setForeground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Se concluye que esta Ciudad puede reducir personal e invertirlo en otros aspectos de la empresa");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(103, 22));
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 270, 120));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 650, 10));

        jLabelMatrizInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMatrizInicial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatrizInicial.setText("Cantidad De Paquetes Por Ciudad");
        add(jLabelMatrizInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jTextAreaCiudad.setEditable(false);
        jTextAreaCiudad.setColumns(20);
        jTextAreaCiudad.setRows(5);
        jScrollPaneUsuario1.setViewportView(jTextAreaCiudad);

        add(jScrollPaneUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 270, 50));

        jLabelMatrizActualizada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMatrizActualizada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatrizActualizada.setText("Localidad con Mayor Envios");
        add(jLabelMatrizActualizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jTextAreaCiudad1.setEditable(false);
        jTextAreaCiudad1.setColumns(20);
        jTextAreaCiudad1.setRows(5);
        jScrollPaneUsuario.setViewportView(jTextAreaCiudad1);

        add(jScrollPaneUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, 50));

        jLabelMatrizActualizada1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMatrizActualizada1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatrizActualizada1.setText("Localidad con Llegada mayor");
        add(jLabelMatrizActualizada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jTextAreaCiudad2.setEditable(false);
        jTextAreaCiudad2.setColumns(20);
        jTextAreaCiudad2.setRows(5);
        jScrollPaneUsuario2.setViewportView(jTextAreaCiudad2);

        add(jScrollPaneUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 270, 50));

        jLabelTitulo1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("Bienvenidos a la Mineria de Datos");
        jLabelTitulo1.setPreferredSize(new java.awt.Dimension(103, 22));
        add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, -1));

        jLabelTitulo2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setText("Se concluye que esta ciudad requiere de mayor personal tecnico y administrativo para la gestion de paqueteria");
        jLabelTitulo2.setEnabled(false);
        jLabelTitulo2.setPreferredSize(new java.awt.Dimension(103, 22));
        add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, 120));
        jLabelTitulo2.getAccessibleContext().setAccessibleDescription("");

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMatrizActualizada;
    private javax.swing.JLabel jLabelMatrizActualizada1;
    private javax.swing.JLabel jLabelMatrizInicial;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JScrollPane jScrollPaneUsuario;
    private javax.swing.JScrollPane jScrollPaneUsuario1;
    private javax.swing.JScrollPane jScrollPaneUsuario2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaCiudad;
    private javax.swing.JTextArea jTextAreaCiudad1;
    private javax.swing.JTextArea jTextAreaCiudad2;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        Jedis jedis = new Jedis("192.168.56.101"); 
        String  [] nombreloca  = {"Usaquen","Chapinero","Santa fe","San Cristobal","Usme","Tunjuelito","Bosa","Ciudad Kennedy","Fontibon,","Engativa","Suba","Barrios Unidos","Teusaquillo","Los martires","Antonio Nariño","Puente Aranda","Candelaria","Candelaria","Rafael Uribe","Ciudad Bolivar","Sumapaz"};
        System.out.println(""+nombreloca[0]);
        System.out.println(""+jedis.select(0));
        int f,g=0;
        Set<String> com = jedis.keys("100*");
        Object [] com2 = com.toArray();
        int []  Origen =  new int [20];
        int [] Destino =  new int [20];
        
        for (Object com21 : com2) {
            System.out.println("------------------------------------");
            jTextAreaCiudad.append("Llave:" + com21);
            f = Integer.parseInt(jedis.hget(com21.toString(), "origen"));
            jTextAreaCiudad.append("Origen: "+f);
            Origen[f-1]=Origen[f-1] +1;
            f = Integer.parseInt(jedis.hget(com21.toString(), "destino"));
            jTextAreaCiudad.append("Destino: "+f);
            Destino[f-1]=Destino[f-1] +1;
            System.out.println("------------------------------------");
        }
       int locadestino =1;
       int locaorigen = 1;
       int posicion2=0;
       int posicion1= 0 ;
       
        ///////////////////////////////////////////////////////////////////////////////////////
        for(int d=0;d<20;d++){
           if(Destino[d]>0){
               if (Destino[d]>locadestino){
               locadestino=Destino[d];
               posicion1 = d;
               }
            //System.out.println("Origen en la posicion " +(d+1)+ " "+Destino[d]);
           //System.out.println("Destno en la posicion " +(d+1)+ " "+Destino[d]);
           }           
        }       
        jTextAreaCiudad1.append("Numero localidad: "+(posicion1+1));
        jTextAreaCiudad1.append(" La localidad en la que mas se entregan paquetes ");
        jTextAreaCiudad1.append("Numero de paguetes : "+locadestino+" Localidad :"+nombreloca[posicion1]);
        System.out.println("_______________________________________________");
        
        ////////////////////////////////////////////////////////////////////////////////////7
        for(int d=0;d<20;d++){
                if(Origen[d]>0){
                    if (Origen[d]>locaorigen){
                    locaorigen=Origen[d];
                    posicion2 = d;
                    }
                System.out.println("Origen en la posicion " +(d+1)+ " "+Origen[d]);
                //System.out.println("Destno en la posicion " +(d+1)+ " "+Destino[d]);
                }           
         }       jTextAreaCiudad2.append("Numero localidad: "+(posicion2+1));
                 jTextAreaCiudad2.append("La localidad en la que mas dejan pedidos para entregar");
                 jTextAreaCiudad2.append("Numero de paguetes : "+locaorigen+" Localidad :"+nombreloca[posicion2]);
         }   

}
