/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.vista;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sala1
 */
public class RegistroEnvioPanel extends javax.swing.JPanel {

    private final PrincipalFrame principalFrame;

    /**
     * Creates new form RegistroPanel
     *
     * @param principalFrame
     */
    public RegistroEnvioPanel(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelCosto = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonRegistro = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAyuda = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabelDatosPaquete = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jDateFechaEntrega = new com.toedter.calendar.JDateChooser();
        jLabelDatosRemitente = new javax.swing.JLabel();
        jLabelNombreRemitente = new javax.swing.JLabel();
        jLabelTelefonoRemitente = new javax.swing.JLabel();
        jTextFieldNombreRemitente = new javax.swing.JTextField();
        jTextFieldTelefonoRemitente = new javax.swing.JTextField();
        jLabelCedulaRemitente = new javax.swing.JLabel();
        jTextFieldCedulaRemitente = new javax.swing.JTextField();
        jLabelEdadRemitente = new javax.swing.JLabel();
        jTextFieldEdadRemitente = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelDatosDestinatario = new javax.swing.JLabel();
        jLabelNombreDestinatario = new javax.swing.JLabel();
        jTextFieldNombreDestinatario = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefonoDestinatario = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jLabelEdadDestinatario = new javax.swing.JLabel();
        jTextFieldCedulaDestinatario = new javax.swing.JTextField();
        jTextFieldEdadDestinatario = new javax.swing.JTextField();
        comlocaOrigen = new javax.swing.JComboBox<>();
        comlocaDestino = new javax.swing.JComboBox<>();
        jLabelFecha1 = new javax.swing.JLabel();
        jLabelFecha2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setForeground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Registrar Envio");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(103, 22));
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 11, 150, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 456, -1));

        jLabelCodigo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Codigo:");
        add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 284, 49, -1));
        add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 281, 140, -1));

        jLabelCosto.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCosto.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabelCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 284, 51, -1));

        jLabelPeso.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelPeso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeso.setText("Peso (Kg)");
        add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 106, -1));
        add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 290, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 460, 9));

        jButtonRegistro.setText("Registro");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });
        add(jButtonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 106, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 104, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, -1));

        jButtonAyuda.setText("Ayuda");
        jButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaActionPerformed(evt);
            }
        });
        add(jButtonAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 90, -1));

        jLabelFecha.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Origen");
        add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, -1));

        jLabelDatosPaquete.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosPaquete.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosPaquete.setText("Datos del Paquete");
        add(jLabelDatosPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 245, 460, 10));
        add(jDateFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 110, 20));

        jLabelDatosRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosRemitente.setText("Datos del Remitente");
        add(jLabelDatosRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelNombreRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelNombreRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreRemitente.setText("Nombre:");
        add(jLabelNombreRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelTelefonoRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelTelefonoRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefonoRemitente.setText("Telefono:");
        add(jLabelTelefonoRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        add(jTextFieldNombreRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 176, -1));
        add(jTextFieldTelefonoRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 178, -1));

        jLabelCedulaRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCedulaRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCedulaRemitente.setText("Cedula:");
        add(jLabelCedulaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));
        add(jTextFieldCedulaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 120, -1));

        jLabelEdadRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelEdadRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadRemitente.setText("Edad:");
        add(jLabelEdadRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        add(jTextFieldEdadRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, 460, 10));

        jLabelDatosDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosDestinatario.setText("Datos del Destinatario");
        add(jLabelDatosDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabelNombreDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelNombreDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreDestinatario.setText("Nombre:");
        add(jLabelNombreDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 180, -1, -1));
        add(jTextFieldNombreDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, -1));

        jLabelTelefono.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono:");
        add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 211, -1, -1));
        add(jTextFieldTelefonoDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 170, -1));

        jLabelCedula.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCedula.setText("Cedula:");
        add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabelEdadDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelEdadDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadDestinatario.setText("Edad:");
        add(jLabelEdadDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        add(jTextFieldCedulaDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 180, 120, -1));
        add(jTextFieldEdadDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 210, 120, -1));

        comlocaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usaquen", "Chapinero", "Santa Fe", "San Cristobal", "Usme", "Tunjuelito", "Bosa", "Ciudad Kennedy", "Fontibon ", "Engativa", "Suba", "Barrios Unidos", "Teusaquillo", "Los Martirez", "Antonio Nariño", "Puente Aranda", "Candelaria ", "Rafael Uribe", "Ciudad Bolivar ", "Sumapaz" }));
        comlocaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comlocaOrigenActionPerformed(evt);
            }
        });
        add(comlocaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 130, -1));

        comlocaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usaquen", "Chapinero", "Santa Fe", "San Cristobal", "Usme", "Tunjuelito", "Bosa", "Ciudad Kennedy", "Fontibon ", "Engativa", "Suba", "Barrios Unidos", "Teusaquillo", "Los Martirez", "Antonio Nariño", "Puente Aranda", "Candelaria ", "Rafael Uribe", "Ciudad Bolivar ", "Sumapaz" }));
        comlocaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comlocaDestinoActionPerformed(evt);
            }
        });
        add(comlocaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 310, 110, -1));

        jLabelFecha1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelFecha1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha1.setText("Destino");
        add(jLabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 60, -1));

        jLabelFecha2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelFecha2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha2.setText("Fecha de entrega:");
        add(jLabelFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        principalFrame.irAHome();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        ayuda();
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    private void comlocaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comlocaOrigenActionPerformed

    }//GEN-LAST:event_comlocaOrigenActionPerformed

    private void comlocaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comlocaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comlocaDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comlocaDestino;
    private javax.swing.JComboBox<String> comlocaOrigen;
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegistro;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateFechaEntrega;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCedulaRemitente;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCosto;
    private javax.swing.JLabel jLabelDatosDestinatario;
    private javax.swing.JLabel jLabelDatosPaquete;
    private javax.swing.JLabel jLabelDatosRemitente;
    private javax.swing.JLabel jLabelEdadDestinatario;
    private javax.swing.JLabel jLabelEdadRemitente;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFecha1;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombreDestinatario;
    private javax.swing.JLabel jLabelNombreRemitente;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoRemitente;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldCedulaDestinatario;
    private javax.swing.JTextField jTextFieldCedulaRemitente;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEdadDestinatario;
    private javax.swing.JTextField jTextFieldEdadRemitente;
    private javax.swing.JTextField jTextFieldNombreDestinatario;
    private javax.swing.JTextField jTextFieldNombreRemitente;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldTelefonoDestinatario;
    private javax.swing.JTextField jTextFieldTelefonoRemitente;
    // End of variables declaration//GEN-END:variables

    public boolean validar() {
        if (this.jTextFieldCodigo.getText().equals("")) {
            return false;
        }  else if (this.jTextFieldPeso.getText().equals("")) {
            return false;
        } else if (this.jTextFieldCedulaDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldCedulaRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldNombreDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldNombreRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldEdadDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldEdadRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldTelefonoDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldTelefonoRemitente.getText().equals("")) {
            return false;
        }else {
            return true;
        } 
    }

    private void limpiar() {
        this.jTextFieldCodigo.setText("");
        this.jTextFieldCedulaDestinatario.setText("");
        this.jTextFieldCedulaRemitente.setText("");
        this.jTextFieldNombreDestinatario.setText("");
        this.jTextFieldNombreRemitente.setText("");
        this.jTextFieldNombreRemitente.requestFocus();
        this.jTextFieldEdadDestinatario.setText("");
        this.jTextFieldEdadRemitente.setText("");
        this.jTextFieldTelefonoDestinatario.setText("");
        this.jTextFieldTelefonoRemitente.setText("");
        this.comlocaOrigen.setSelectedIndex(0);
        this.comlocaDestino.setSelectedIndex(0);
        this.jTextFieldPeso.setText("");
    }

    private void ayuda() {
        String mensaje = "Debe llenar cada uno de los campos requeridos.\n"
                + "si el campo esta vacio debe registrar la informacion,\n"
                + "si la informacion ya esta registrada debe crear una nueva.\n"
                + "En el caso de que sus datos no se hallan registrado deberá repetir\n"
                + "el proceso o ponerse en contacto con: admin@sgm.com";
        JOptionPane.showMessageDialog(this, mensaje, "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }
  
    public void registrar() {
        DateFormat df = new SimpleDateFormat("d/MM/yyyy");
        Date today = jDateFechaEntrega.getDate();
        if (validar()) {
            String codigo = jTextFieldCodigo.getText();
            int codigoPaquete = Integer.parseInt(codigo);
            if (!principalFrame.existeEnvio(codigo)) {
                String NombresRemitente = jTextFieldNombreRemitente.getText();
                String cedula = jTextFieldCedulaRemitente.getText();
                String edad = jTextFieldEdadRemitente.getText();
                String teléfono = jTextFieldTelefonoRemitente.getText();
                String NombreDestinatario = jTextFieldNombreDestinatario.getText();
                String cedula1 = jTextFieldCedulaDestinatario.getText();
                String edad1 = jTextFieldEdadDestinatario.getText();
                String teléfono1 = jTextFieldTelefonoDestinatario.getText();
                String Fechaentrega = df.format(today);
                String peso = jTextFieldPeso.getText();
                int origen =  (int) comlocaOrigen.getSelectedIndex();
                int destino = (int) comlocaDestino.getSelectedIndex();
                if (principalFrame.registrarEnvio(codigoPaquete, NombresRemitente, cedula, edad, teléfono, NombreDestinatario, cedula1, edad1, teléfono1,  Fechaentrega, peso,origen,destino)) {
                    JOptionPane.showMessageDialog(this, "Usuario "+codigo+" regeitrado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    principalFrame.irAHome();
                } else {
                    JOptionPane.showMessageDialog(this, "no se pudo registrar al usuario", "Registro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El Nickname ya Existe", "Registro", JOptionPane.WARNING_MESSAGE);
                jTextFieldCodigo.setText("");
                jTextFieldCodigo.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos requeridos para crear su cuenta", "Registro", JOptionPane.WARNING_MESSAGE);
        }
    }

}
