/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author sala1
 */
public class RegistroEstadoPanel extends javax.swing.JPanel {

    private final PrincipalFrame principalFrame;

    /**
     * Creates new form RegistroPanel
     *
     * @param principalFrame
     */
    public RegistroEstadoPanel(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelFecha = new javax.swing.JLabel();
        jLabelDatosPaquete = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jDateFechaEntrega = new com.toedter.calendar.JDateChooser();
        jLabelDatosRemitente = new javax.swing.JLabel();
        jLabelNombreRemitente = new javax.swing.JLabel();
        jLabelTelefonoRemitente = new javax.swing.JLabel();
        jTextFieldNombreRemitente = new javax.swing.JTextField();
        jTextFieldTelefonoRemitente = new javax.swing.JTextField();
        jLabelCedulaRemitente = new javax.swing.JLabel();
        jTextFieldCedulaRemitente = new javax.swing.JTextField();
        jLabelEdadRemitente = new javax.swing.JLabel();
        jTextFieldEdadRemitente = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelDatosDestinatario = new javax.swing.JLabel();
        jLabelNombreDestinatario = new javax.swing.JLabel();
        jTextFieldNombreDestinatario = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefonoDestinatario = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jLabelEdadDestinatario = new javax.swing.JLabel();
        jTextFieldCedulaDestinatario = new javax.swing.JTextField();
        jTextFieldEdadDestinatario = new javax.swing.JTextField();
        jLabelObservaciones = new javax.swing.JLabel();
        jLabelEstados1 = new javax.swing.JLabel();
        jLabelFecha1 = new javax.swing.JLabel();
        jDateFechaEntrega1 = new com.toedter.calendar.JDateChooser();
        jComboBoxObservaciones = new javax.swing.JComboBox<>();
        jComboBoxEstados = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setForeground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Detalles del Envio");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(103, 22));
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 11, 170, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 456, -1));

        jLabelCodigo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Codigo:");
        add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 284, 49, -1));
        add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 281, 203, -1));

        jLabelPeso.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelPeso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeso.setText("Peso (Kg)");
        add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 106, -1));
        add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 290, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 460, 9));

        jLabelFecha.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha de entrega:");
        add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, -1));

        jLabelDatosPaquete.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosPaquete.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosPaquete.setText("Datos del Paquete");
        add(jLabelDatosPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 245, 460, 10));
        add(jDateFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 290, 20));

        jLabelDatosRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosRemitente.setText("Datos del Remitente");
        add(jLabelDatosRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelNombreRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelNombreRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreRemitente.setText("Nombre:");
        add(jLabelNombreRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelTelefonoRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelTelefonoRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefonoRemitente.setText("Telefono:");
        add(jLabelTelefonoRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        add(jTextFieldNombreRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 176, -1));
        add(jTextFieldTelefonoRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 178, -1));

        jLabelCedulaRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCedulaRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCedulaRemitente.setText("Cedula:");
        add(jLabelCedulaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));
        add(jTextFieldCedulaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 120, -1));

        jLabelEdadRemitente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelEdadRemitente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadRemitente.setText("Edad:");
        add(jLabelEdadRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        add(jTextFieldEdadRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, 460, 10));

        jLabelDatosDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelDatosDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosDestinatario.setText("Datos del Destinatario");
        add(jLabelDatosDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabelNombreDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelNombreDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreDestinatario.setText("Nombre:");
        add(jLabelNombreDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 180, -1, -1));
        add(jTextFieldNombreDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, -1));

        jLabelTelefono.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono:");
        add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 211, -1, -1));
        add(jTextFieldTelefonoDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 170, -1));

        jLabelCedula.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCedula.setText("Cedula:");
        add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabelEdadDestinatario.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelEdadDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadDestinatario.setText("Edad:");
        add(jLabelEdadDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        add(jTextFieldCedulaDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 180, 120, -1));
        add(jTextFieldEdadDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 210, 120, -1));

        jLabelObservaciones.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservaciones.setText("Observaciones");
        add(jLabelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jLabelEstados1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelEstados1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstados1.setText("Estados");
        add(jLabelEstados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabelFecha1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabelFecha1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha1.setText("Fecha Estimada de llegada");
        add(jLabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 160, -1));
        add(jDateFechaEntrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 230, 20));

        jComboBoxObservaciones.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jComboBoxObservaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Observaciones" }));
        jComboBoxObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxObservacionesActionPerformed(evt);
            }
        });
        add(jComboBoxObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 130, -1));

        jComboBoxEstados.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jComboBoxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados" }));
        jComboBoxEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadosActionPerformed(evt);
            }
        });
        add(jComboBoxEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 130, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxObservacionesActionPerformed

    private void jComboBoxEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBoxEstados;
    private javax.swing.JComboBox<String> jComboBoxObservaciones;
    private com.toedter.calendar.JDateChooser jDateFechaEntrega;
    private com.toedter.calendar.JDateChooser jDateFechaEntrega1;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCedulaRemitente;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDatosDestinatario;
    private javax.swing.JLabel jLabelDatosPaquete;
    private javax.swing.JLabel jLabelDatosRemitente;
    private javax.swing.JLabel jLabelEdadDestinatario;
    private javax.swing.JLabel jLabelEdadRemitente;
    private javax.swing.JLabel jLabelEstados1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFecha1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombreDestinatario;
    private javax.swing.JLabel jLabelNombreRemitente;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoRemitente;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldCedulaDestinatario;
    private javax.swing.JTextField jTextFieldCedulaRemitente;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEdadDestinatario;
    private javax.swing.JTextField jTextFieldEdadRemitente;
    private javax.swing.JTextField jTextFieldNombreDestinatario;
    private javax.swing.JTextField jTextFieldNombreRemitente;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldTelefonoDestinatario;
    private javax.swing.JTextField jTextFieldTelefonoRemitente;
    // End of variables declaration//GEN-END:variables

    public boolean validar() {
        if (this.jTextFieldCodigo.getText().equals("")) {
            return false;
        } else if (this.jTextFieldPeso.getText().equals("")) {
            return false;
        } else if (this.jTextFieldCedulaDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldCedulaRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldNombreDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldNombreRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldEdadDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldEdadRemitente.getText().equals("")) {
            return false;
        } else if (this.jTextFieldTelefonoDestinatario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldTelefonoRemitente.getText().equals("")) {
            return false;
        }else {
            return true;
        } 
    }

    private void limpiar() {
        this.jTextFieldCodigo.setText("");
        this.jTextFieldCedulaDestinatario.setText("");
        this.jTextFieldCedulaRemitente.setText("");
        this.jTextFieldNombreDestinatario.setText("");
        this.jTextFieldNombreRemitente.setText("");
        this.jTextFieldNombreRemitente.requestFocus();
        this.jTextFieldEdadDestinatario.setText("");
        this.jTextFieldEdadRemitente.setText("");
        this.jTextFieldTelefonoDestinatario.setText("");
        this.jTextFieldTelefonoRemitente.setText("");
        this.jTextFieldPeso.setText("");
    }

    private void cargarDatos() {
        String respuesta = JOptionPane.showInputDialog(null, "Ingrese el Codigo del Paquete ", "Modificar", JOptionPane.DEFAULT_OPTION);
        if (principalFrame.existeEnvio(respuesta)) {
                String[] datosPaquete = principalFrame.obtenerDatosDelEnvio(respuesta);
                jTextFieldCodigo.setText(datosPaquete[0]);
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNombreRemitente.setText(datosPaquete[1]);
                jTextFieldCedulaRemitente.setText(datosPaquete[2]);
                jTextFieldEdadRemitente.setText(datosPaquete[3]);
                jTextFieldTelefonoRemitente.setText(datosPaquete[4]);
                jTextFieldNombreDestinatario.setText(datosPaquete[5]);
                jTextFieldCedulaDestinatario.setText(datosPaquete[6]);
                jTextFieldEdadDestinatario.setText(datosPaquete[7]);
                jTextFieldTelefonoDestinatario.setText(datosPaquete[8]);
                jDateFechaEntrega.setDateFormatString(datosPaquete[9]);
                jTextFieldPeso.setText(datosPaquete[10]);
                jDateFechaEntrega1.setDateFormatString(datosPaquete[11]);
                //String[] datosPaquete1 = principalFrame.obtenerDatosDelEstado(respuesta);
        } else {
                JOptionPane.showMessageDialog(this, "No coincide el codigo ingresado con algun paquete existente", "Modificar", JOptionPane.WARNING_MESSAGE);
                principalFrame.irAHomePanelRegistrador();
        }                
    }

}
