/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.vista;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sala1
 */
public class RegistroPanel extends javax.swing.JPanel {

    private final PrincipalFrame principalFrame;

    /**
     * Creates new form RegistroPanel
     *
     * @param principalFrame
     */
    public RegistroPanel(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNickname = new javax.swing.JLabel();
        jTextFieldNickname = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelContrasenia = new javax.swing.JLabel();
        jPasswordFieldContrasenia = new javax.swing.JPasswordField();
        jLabelConfirma = new javax.swing.JLabel();
        jPasswordFieldConfirma = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonRegistro = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAyuda = new javax.swing.JButton();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jComboBoxMembresia = new javax.swing.JComboBox<>();
        jLabelMembresia = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setForeground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("REGISTRO");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(103, 22));
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 6, 150, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 350, -1));

        jLabelNombre.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombres:");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 118, -1));
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 47, 194, -1));

        jLabelNickname.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jLabelNickname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNickname.setText("NickName:");
        add(jLabelNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 118, -1));
        add(jTextFieldNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 109, 194, -1));

        jLabelCorreo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo:");
        add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 118, -1));
        add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 140, 194, -1));

        jLabelContrasenia.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jLabelContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContrasenia.setText("Contraseña");
        add(jLabelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, 118, -1));
        add(jPasswordFieldContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 166, 194, -1));

        jLabelConfirma.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jLabelConfirma.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirma.setText("Confirma su contraseña:");
        add(jLabelConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        add(jPasswordFieldConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 197, 193, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 259, 340, -1));

        jButtonRegistro.setText("Registro");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });
        add(jButtonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 272, -1, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 272, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 272, -1, -1));

        jButtonAyuda.setText("Ayuda");
        jButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaActionPerformed(evt);
            }
        });
        add(jButtonAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 272, -1, -1));

        jLabelApellido.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellidos:");
        add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 118, -1));
        add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 78, 194, -1));

        jComboBoxMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de Usuario", "Administrador", "Registrador" }));
        jComboBoxMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMembresiaActionPerformed(evt);
            }
        });
        add(jComboBoxMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 228, 192, -1));

        jLabelMembresia.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jLabelMembresia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMembresia.setText("Tipo de Usuario");
        add(jLabelMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 117, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        principalFrame.irAInicioDeSesion();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        ayuda();
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    private void jComboBoxMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMembresiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JComboBox<String> jComboBoxMembresia;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelConfirma;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMembresia;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPasswordFieldConfirma;
    private javax.swing.JPasswordField jPasswordFieldContrasenia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNickname;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    public boolean validar() {
        if (this.jTextFieldNombre.getText().equals("")) {
            return false;
        } else if (this.jTextFieldApellido.getText().equals("")) {
            return false;
        } else if (this.jTextFieldNickname.getText().equals("")) {
            return false;
        } else if (this.jTextFieldCorreo.getText().equals("")) {
            return false;
        } else if (this.jPasswordFieldContrasenia.getText().equals("")) {
            return false;
        } else if (this.jPasswordFieldConfirma.getText().equals("")) {
            return false;
        } else if (this.jPasswordFieldContrasenia.getText().equals(this.jPasswordFieldConfirma.getText())) {
            return true;
        } else if (this.jComboBoxMembresia.getSelectedIndex() == 0) {
            return false;
        }else {
            return false;
        }
    }

    private void limpiar() {
        this.jTextFieldNombre.setText("");
        this.jTextFieldNombre.requestFocus();
        this.jTextFieldApellido.setText("");
        this.jTextFieldNickname.setText("");
        this.jTextFieldCorreo.setText("");
        this.jPasswordFieldContrasenia.setText("");
        this.jPasswordFieldConfirma.setText("");
        this.jComboBoxMembresia.setSelectedIndex(0);
    }

    private void ayuda() {
        String mensaje = "Debe llenar cada uno de los campos requeridos.\n"
                + "si el campo esta vacio debe registrar la informacion,\n"
                + "si la informacion ya esta registrada debe crear una nueva.\n"
                + "En el caso de que sus datos no se hallan registrado deberá repetir\n"
                + "el proceso o ponerse en contacto con: cmrodriguez67@ucatolica.edu.co";
        JOptionPane.showMessageDialog(this, mensaje, "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }
  
    public void registrar() {
        if (validar()) {
            String nickName = jTextFieldNickname.getText();
            if (!principalFrame.existeUsuario(nickName)) {
                String nombre = jTextFieldNombre.getText();
                String apellido = jTextFieldApellido.getText();
                String correo = jTextFieldCorreo.getText();
                int tipo = Select( (String) jComboBoxMembresia.getSelectedItem());
                String contrasenia = new String(jPasswordFieldContrasenia.getPassword());
                if (principalFrame.registrarUsuario(nombre, apellido, nickName, correo, contrasenia,tipo)) {
                    JOptionPane.showMessageDialog(this, "Usuario "+nickName+" regeitrado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    principalFrame.irAInicioDeSesion();
                } else {
                    JOptionPane.showMessageDialog(this, "no se pudo registrar al usuario", "Registro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El Nickname ya Existe", "Registro", JOptionPane.WARNING_MESSAGE);
                jTextFieldNickname.setText("");
                jTextFieldNickname.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos requeridos para crear su cuenta", "Registro", JOptionPane.WARNING_MESSAGE);
        }
    }

    private int Select(String string) {
        if (string.equals("Administrador")){
            return 1;
        }else{
            return 0;
        }
    }

}
